version: '3'
services:

  web:
    # image: frickreich/gandhi
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install bcrypt; npm run prod'
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      DATABASE_URL: "mongodb://mongo:27017/db"
      PORT: 8080
      CDN_ENDPOINT: "fra1.digitaloceanspaces.com"
      CDN_KEY: "D3ZQKBHRIL3BSTCQSB7J"
      CDN_SECRET: "OpcljBqGrL7yrURH0y+EBo8N6uy1i6JAkpgPf+LTpW0"

  mongo:
    image: mongo:3
    container_name: mongo
    command: mongod --smallfiles --bind_ip_all
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - all

  mongo-express:
    image: "mongo-express:latest"
    container_name: mongo-express
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongo
    networks:
      - all
networks:
  all: